extract = 'total_dyn_inst: (\d+)'
benchmarks = './test/benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.myopt]
pipeline = [
    "bril2json",
    "python lvn.py",
    "brili -p {args}",
]