__all__ = ['BrilAddInsn','BrilAndInsn',
           'BrilBooleanLiteralInsn','BrilBooleanMathInsn',
           'BrilBranchInsn','BrilConstInsn',
           'BrilDivInsn','BrilEffectOperationInsn',
           'BrilFunctionCallInsn','BrilIdInsn',
           'BrilIntegerLiteralInsn','BrilIntegerMathInsn',
           'BrilJumpInsn','BrilMulInsn',
           'BrilNotInsn','BrilOrInsn',
           'BrilRelationalMathInsn','BrilRetInsn',
           'BrilValueOperationInsn','BrilSubInsn']